ifndef NEXMON_SETUP_ENV
	$(error run 'source setup_env.sh' first in the repository\'s root directory)
endif

GIT_VERSION := $(shell git describe --abbrev=4 --dirty --always --tags)
IFACE ?= wlan0
include ../version.mk
include $(FW_PATH)/definitions.mk

COMMON_SRCS=$(wildcard $(NEXMON_ROOT)/patches/common/*.c)
FW_SRCS=$(wildcard $(FW_PATH)/*.c)

UCODEFILE:=
SPLITPATH=$(subst /, ,$(FW_PATH))
FWUCODE=$(word $(shell expr $(words $(SPLITPATH)) - 1),$(SPLITPATH)).$(lastword $(SPLITPATH)).patch
ALL_UCODES=$(notdir $(wildcard src/*.patch))
UCODES=$(filter %$(FWUCODE),$(ALL_UCODES))
ifeq ($(UCODEFILE),)
UCODEFILE=csi.ucode.$(FWUCODE)
endif

# Every CSI hook is placed at an address that was reverse engineered for one
# specific firmware build - see the __attribute__((at(..., CHIP_VER_x, FW_VER_y)))
# lists in src/ioctl.c and src/csi_extractor.c - and the ucode diff only applies
# to that build's ucode.bin. Build under a firmware version that has neither and
# the hooks are simply dropped: you get a firmware image that flashes fine and
# contains no extractor. That is worth refusing outright, because the failure
# otherwise surfaces much later as "tcpdump sees no CSI" with nothing to point
# at. Without this check make dies at 'No rule to make target
# src/ucode_compressed.c' instead, which says nothing about the real problem.
CSI_PORTS=$(patsubst csi.ucode.%.patch,%,$(ALL_UCODES))
NONBUILD_GOALS=clean clean-firmware csi-stop csi-status restore-wifi reload-driver
ifeq ($(filter $(UCODEFILE),$(UCODES)), )
ifneq ($(filter-out $(NONBUILD_GOALS),$(or $(MAKECMDGOALS),all)), )
$(error nexmon_csi has no CSI port for $(basename $(FWUCODE)). \
  Ported firmware versions: $(CSI_PORTS). \
  On a Raspberry Pi this repository has to be cloned into and built from \
  $$NEXMON_ROOT/patches/bcm43455c0/7_45_189/ - newer 43455 firmware directories \
  exist in nexmon but no CSI addresses have been reversed for them)
endif
endif

LOCAL_SRCS=$(wildcard src/*.c) src/ucode_compressed.c
B43VERSION=b43-v3

OBJS=$(addprefix obj/,$(notdir $(LOCAL_SRCS:.c=.o)) $(notdir $(COMMON_SRCS:.c=.o)) $(notdir $(FW_SRCS:.c=.o)))

CFLAGS= \
	-fplugin=$(CCPLUGIN) \
	-fplugin-arg-nexmon-objfile=$@ \
	-fplugin-arg-nexmon-prefile=gen/nexmon.pre \
	-fplugin-arg-nexmon-chipver=$(NEXMON_CHIP_NUM) \
	-fplugin-arg-nexmon-fwver=$(NEXMON_FW_VERSION_NUM) \
	-fno-strict-aliasing \
	-DNEXMON_CHIP=$(NEXMON_CHIP) \
	-DNEXMON_FW_VERSION=$(NEXMON_FW_VERSION) \
	-DVERSION_PTR=$(VERSION_PTR) \
	-DWLC_UCODE_WRITE_BL_HOOK_ADDR=$(WLC_UCODE_WRITE_BL_HOOK_ADDR) \
	-DHNDRTE_RECLAIM_0_END_PTR=$(HNDRTE_RECLAIM_0_END_PTR) \
	-DHNDRTE_RECLAIM_UCODES_END_PTR=$(HNDRTE_RECLAIM_UCODES_END_PTR) \
	-DWLC_NONMUUCODE_WRITE_BL_HOOK_ADDR=$(WLC_NONMUUCODE_WRITE_BL_HOOK_ADDR) \
	-DNONMUUCODESTART_PTR=$(NONMUUCODESTART_PTR) \
	-DNONMUUCODESIZE_PTR=$(NONMUUCODESIZE_PTR) \
	-DWLC_NONMUUCODEX_WRITE_BL_HOOK_ADDR=$(WLC_NONMUUCODEX_WRITE_BL_HOOK_ADDR) \
	-DNONMUUCODEXSTART_PTR=$(NONMUUCODEXSTART_PTR) \
	-DNONMUUCODEXSIZE_PTR=$(NONMUUCODEXSIZE_PTR) \
	-DWLC_MUUCODE_WRITE_BL_HOOK_ADDR=$(WLC_MUUCODE_WRITE_BL_HOOK_ADDR) \
	-DMUUCODESTART_PTR=$(MUUCODESTART_PTR) \
	-DMUUCODESIZE_PTR=$(MUUCODESIZE_PTR) \
	-DWLC_MUUCODEX_WRITE_BL_HOOK_ADDR=$(WLC_MUUCODEX_WRITE_BL_HOOK_ADDR) \
	-DMUUCODEXSTART_PTR=$(MUUCODEXSTART_PTR) \
	-DMUUCODEXSIZE_PTR=$(MUUCODEXSIZE_PTR) \
	-DTEMPLATERAMSTART_PTR=$(TEMPLATERAMSTART_PTR) \
	-DPATCHSTART=$(PATCHSTART) \
	-DUCODESIZE=$(UCODESIZE) \
	-DRXE_RXHDR_LEN=$(RXE_RXHDR_LEN) \
	-DRXE_RXHDR_EXTRA=$(RXE_RXHDR_EXTRA) \
	-DGIT_VERSION=\"$(GIT_VERSION)\" \
	-DBUILD_NUMBER=\"$$(cat BUILD_NUMBER)\" \
	-Wall -Werror -Wno-unused-function -Wno-unused-variable \
	-O2 -nostdlib -nostartfiles -ffreestanding -mthumb -march=$(NEXMON_ARCH) \
	-ffunction-sections -fdata-sections \
	-I$(NEXMON_ROOT)/patches/include \
	-Iinclude \
	-I$(FW_PATH)

all: $(RAM_FILE)

init: FORCE
	$(Q)if ! test -f BUILD_NUMBER; then echo 0 > BUILD_NUMBER; fi
	$(Q)echo $$(($$(cat BUILD_NUMBER) + 1)) > BUILD_NUMBER
	$(Q)touch src/version.c
	$(Q)make -s -f $(NEXMON_ROOT)/patches/common/header.mk
	$(Q)mkdir -p obj gen log

obj/%.o: src/%.c
	@printf "\033[0;31m  COMPILING\033[0m %s => %s (details: log/compiler.log)\n" $< $@
	$(Q)cat gen/nexmon.pre 2>>log/error.log | gawk '{ if ($$3 != "$@") print; }' > tmp && mv tmp gen/nexmon.pre
	$(Q)$(CC)gcc $(CFLAGS) -c $< -o $@ >>log/compiler.log

obj/%.o: $(NEXMON_ROOT)/patches/common/%.c
	@printf "\033[0;31m  COMPILING\033[0m %s => %s (details: log/compiler.log)\n" $< $@
	$(Q)cat gen/nexmon.pre 2>>log/error.log | gawk '{ if ($$3 != "$@") print; }' > tmp && mv tmp gen/nexmon.pre
	$(Q)$(CC)gcc $(CFLAGS) -c $< -o $@ >>log/compiler.log

obj/%.o: $(FW_PATH)/%.c
	@printf "\033[0;31m  COMPILING\033[0m %s => %s (details: log/compiler.log)\n" $< $@
	$(Q)cat gen/nexmon.pre 2>>log/error.log | gawk '{ if ($$3 != "$@") print; }' > tmp && mv tmp gen/nexmon.pre
	$(Q)$(CC)gcc $(CFLAGS) -c $< -o $@ >>log/compiler.log

gen/nexmon2.pre: $(OBJS)
	@printf "\033[0;31m  PREPARING\033[0m %s => %s\n" "gen/nexmon.pre" $@
	$(Q)cat gen/nexmon.pre | awk '{ if ($$3 != "obj/flashpatches.o" && $$3 != "obj/wrapper.o") { print $$0; } }' > tmp
	$(Q)cat gen/nexmon.pre | awk '{ if ($$3 == "obj/flashpatches.o" || $$3 == "obj/wrapper.o") { print $$0; } }' >> tmp
	$(Q)cat tmp | awk '{ if ($$1 ~ /^0x/) { if ($$3 != "obj/flashpatches.o" && $$3 != "obj/wrapper.o") { if (!x[$$1]++) { print $$0; } } else { if (!x[$$1]) { print $$0; } } } else { print $$0; } }' > gen/nexmon2.pre

gen/nexmon.ld: gen/nexmon2.pre $(OBJS)
	@printf "\033[0;31m  GENERATING LINKER FILE\033[0m gen/nexmon.pre => %s\n" $@
	$(Q)sort gen/nexmon2.pre | gawk -f $(NEXMON_ROOT)/buildtools/scripts/nexmon.ld.awk > $@

gen/nexmon.mk: gen/nexmon2.pre $(OBJS) $(FW_PATH)/definitions.mk
	@printf "\033[0;31m  GENERATING MAKE FILE\033[0m gen/nexmon.pre => %s\n" $@
	$(Q)printf "$(RAM_FILE): gen/patch.elf FORCE\n" > $@
	$(Q)sort gen/nexmon2.pre | \
		gawk -v src_file=gen/patch.elf -f $(NEXMON_ROOT)/buildtools/scripts/nexmon.mk.1.awk | \
		gawk -v ramstart=$(RAMSTART) -f $(NEXMON_ROOT)/buildtools/scripts/nexmon.mk.2.awk >> $@
	$(Q)printf "\nFORCE:\n" >> $@
	$(Q)gawk '!a[$$0]++' $@ > tmp && mv tmp $@

gen/flashpatches.ld: gen/nexmon2.pre $(OBJS)
	@printf "\033[0;31m  GENERATING LINKER FILE\033[0m gen/nexmon.pre => %s\n" $@
	$(Q)sort gen/nexmon2.pre | \
		gawk -f $(NEXMON_ROOT)/buildtools/scripts/flashpatches.ld.awk > $@

FLASHPATCHES=flashpatches.mk.awk
gen/flashpatches.mk: gen/nexmon2.pre $(OBJS) $(FW_PATH)/definitions.mk
	@printf "\033[0;31m  GENERATING MAKE FILE\033[0m gen/nexmon.pre => %s\n" $@
	$(Q)cat gen/nexmon2.pre | gawk \
		-v fp_data_base=$(FP_DATA_BASE) \
		-v fp_config_base=$(FP_CONFIG_BASE) \
		-v fp_data_end_ptr=$(FP_DATA_END_PTR) \
		-v fp_config_base_ptr_1=$(FP_CONFIG_BASE_PTR_1) \
		-v fp_config_end_ptr_1=$(FP_CONFIG_END_PTR_1) \
		-v fp_config_base_ptr_2=$(FP_CONFIG_BASE_PTR_2) \
		-v fp_config_end_ptr_2=$(FP_CONFIG_END_PTR_2) \
		-v ramstart=$(RAMSTART) \
		-v out_file=$(RAM_FILE) \
		-v src_file=gen/patch.elf \
		-f $(NEXMON_ROOT)/buildtools/scripts/$(FLASHPATCHES) > $@

gen/memory.ld: $(FW_PATH)/definitions.mk
	@printf "\033[0;31m  GENERATING LINKER FILE\033[0m %s\n" $@
	$(Q)printf "rom : ORIGIN = 0x%08x, LENGTH = 0x%08x\n" $(ROMSTART) $(ROMSIZE) > $@
	$(Q)printf "ram : ORIGIN = 0x%08x, LENGTH = 0x%08x\n" $(RAMSTART) $(RAMSIZE) >> $@
	$(Q)printf "patch : ORIGIN = 0x%08x, LENGTH = 0x%08x\n" $(PATCHSTART) $(PATCHSIZE) >> $@
	$(Q)printf "ucode : ORIGIN = 0x%08x, LENGTH = 0x%08x\n" $(UCODESTART) $$(($(FP_CONFIG_BASE) - $(UCODESTART))) >> $@
	$(Q)printf "fpconfig : ORIGIN = 0x%08x, LENGTH = 0x%08x\n" $(FP_CONFIG_BASE) $(FP_CONFIG_SIZE) >> $@

gen/patch.elf: patch.ld gen/nexmon.ld gen/flashpatches.ld gen/memory.ld $(OBJS)
	@printf "\033[0;31m  LINKING OBJECTS\033[0m => %s (details: log/linker.log, log/linker.err)\n" $@
	$(Q)$(CC)ld -T $< -o $@ --gc-sections --print-gc-sections -M >>log/linker.log 2>>log/linker.err

$(RAM_FILE): init gen/patch.elf $(FW_PATH)/$(RAM_FILE) gen/nexmon.mk gen/flashpatches.mk
	$(Q)cp $(FW_PATH)/$(RAM_FILE) $@
	@printf "\033[0;31m  APPLYING FLASHPATCHES\033[0m gen/flashpatches.mk => %s (details: log/flashpatches.log)\n" $@
	$(Q)make -f gen/flashpatches.mk >>log/flashpatches.log 2>>log/flashpatches.log
	@printf "\033[0;31m  APPLYING PATCHES\033[0m gen/nexmon.mk => %s (details: log/patches.log)\n" $@
	$(Q)make -f gen/nexmon.mk >>log/patches.log 2>>log/patches.log

###################################################################
# ucode compression related
###################################################################
ifneq ($(filter $(UCODEFILE),$(UCODES)), )
gen/ucode.asm: $(FW_PATH)/ucode.bin
	@printf "\033[0;31m  DISASSEMBLING UCODE\033[0m %s => %s\n" $< $@
	$(Q)$(NEXMON_ROOT)/buildtools/$(B43VERSION)/disassembler/b43-dasm $< $@ --arch 15 --format raw-le32 2>log/disass.log
	$(Q)$(NEXMON_ROOT)/buildtools/$(B43VERSION)/debug/b43-beautifier --asmfile $@ --defs $(NEXMON_ROOT)/buildtools/$(B43VERSION)/debug/include > tmp && mv tmp $@

src/$(UCODEFILE:.patch=.asm): src/$(UCODEFILE) gen/ucode.asm
	@printf "\033[0;31m  PATCHING UCODE\033[0m %s => %s\n" $< $@
	$(Q)cp gen/ucode.asm $@
	$(Q)patch -p1 $@ $< >log/patch.log || true

gen/ucode.bin: src/$(UCODEFILE:.patch=.asm)
	@printf "\033[0;31m  ASSEMBLING UCODE\033[0m %s => %s\n" $< $@
ifneq ($(wildcard $(NEXMON_ROOT)/buildtools/$(B43VERSION)/assembler/b43-asm.bin), )
	$(Q)PATH="$(PATH):$(NEXMON_ROOT)/buildtools/$(B43VERSION)/assembler" $(NEXMON_ROOT)/buildtools/$(B43VERSION)/assembler/b43-asm $< $@ --cpp-args -DRXE_RXHDR_LEN=$(RXE_RXHDR_LEN) -- --format raw-le32 2>log/ass.log
else
	$(error Warning: please compile b43-asm.bin first)
endif

gen/ucode_compressed.bin: gen/ucode.bin
	@printf "\033[0;31m  COMPRESSING UCODE\033[0m %s => %s\n" $< $@
	$(Q)cat $< | $(ZLIBFLATE) > $@

src/ucode_compressed.c: gen/ucode_compressed.bin
	@printf "\033[0;31m  GENERATING C FILE\033[0m %s => %s\n" $< $@
	$(Q)printf "#pragma NEXMON targetregion \"ucode\"\n\n" > $@
	$(Q)cd $(dir $<) && xxd -i $(notdir $<) >> $(shell pwd)/$@

else
gen/ucode.asm:
ifneq ($(UCODEFILE),)
	@printf "\033[0;31m  WARNING\033[0m uncompatible or non-existing ucodefile \"%s\" selected, use \"make UCODEFILE=<filename>\" where filename one of: %s\n" $(UCODEFILE) $(UCODES)
else
	@printf "\033[0;31m  WARNING\033[0m empty ucodefile specified, use \"make UCODEFILE=<filename>\" where filename one of: %s\n" $(UCODEFILE) $(UCODES)
endif
	$(Q)exit 1
endif

src/templateram.c: $(FW_PATH)/templateram.bin
	@printf "\033[0;31m  GENERATING C FILE\033[0m %s => %s\n" $< $@
	$(Q)printf "#pragma NEXMON targetregion \"ucode\"\n\n" > $@
	$(Q)cd $(dir $<) && xxd -i $(notdir $<) >> $(shell pwd)/$@

###################################################################

# /proc/cpuinfo only carries a Model line thanks to a Raspberry Pi downstream
# kernel patch, so it vanishes under a mainline or Ubuntu arm64 kernel on the
# very same board. The device tree model is published by the firmware itself and
# is there either way, so prefer it and keep cpuinfo as the fallback.
is-rpi: FORCE
	$(Q)model=$$(tr -d '\0' < /proc/device-tree/model 2>/dev/null); \
	if [ -z "$$model" ]; then \
	    model=$$(sed -n 's/^Model[[:space:]]*:[[:space:]]*//p' /proc/cpuinfo 2>/dev/null); \
	fi; \
	case "$$model" in \
	    *"Raspberry Pi"*) ;; \
	    *) echo "error: this target has to run on the Raspberry Pi itself (detected: $${model:-unknown device})" >&2; \
	       echo "Build the firmware image here with 'make -f Makefile.rpi' and install it on the Pi." >&2; \
	       exit 1 ;; \
	esac

reload-driver: is-rpi
	@printf "\033[0;31m  RELOADING DRIVER\033[0m %s\n" "brcmfmac"
	$(Q)sudo utils/reload-brcmfmac.sh -i $(IFACE)

unmanage: is-rpi
	@printf "\033[0;31m  NetworkManager DISCONNECT\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli dev disconnect $(IFACE)
	@printf "\033[0;31m  NetworkManager UNMANAGE\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli dev set $(IFACE) managed no
	@printf "\033[0;31m  NetworkManager RADIO OFF\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli radio wifi off
	@printf "\033[0;31m  UNBLOCK RADIO\033[0m\n"
	$(Q)sudo rfkill unblock wifi

# 'ip' replaces ifconfig here because net-tools is not part of a default
# bookworm or trixie install, and nexutil needs root like every other write.
reload-full: reload-driver
	@printf "\033[0;31m  BRINGUP INTERFACE\033[0m %s\n" "$(IFACE)"
	$(Q)sudo ip link set $(IFACE) up
	@printf "\033[0;31m  DISABLE\033[0m Power Save\n"
	$(Q)sudo iw dev $(IFACE) set power_save off
	$(Q)sudo nexutil -I$(IFACE) -s86 -i -v0

# nexutil has to speak a transport the running driver serves. Its default ioctl
# transport and its -DUSE_NETLINK transport both need nexmon's patched brcmfmac,
# which exists only for kernels 4.19, 5.4 and 5.10. Every Raspberry Pi OS past
# those loads the stock driver, which takes firmware commands as nl80211 vendor
# commands - hence USE_VENDOR_CMD=1. Build it wrong and nexutil still exits 0
# while configuring nothing, so this is worth getting right once.
# 'clean' first: objects left from an earlier build keep the old transport.
install-nexutil: is-rpi
	@printf "\033[0;31m  BUILDING\033[0m %s\n" "nexutil (USE_VENDOR_CMD=1)"
	$(Q)make -C $(NEXMON_ROOT)/utilities/nexutil clean
	$(Q)make -C $(NEXMON_ROOT)/utilities/nexutil USE_VENDOR_CMD=1
	@printf "\033[0;31m  INSTALLING\033[0m %s\n" "nexutil"
	$(Q)sudo make -C $(NEXMON_ROOT)/utilities/nexutil USE_VENDOR_CMD=1 install

install-csi-tools: is-rpi install-nexutil
	@printf "\033[0;31m  BUILDING\033[0m %s\n" "makecsiparams"
	$(Q)make -C utils/makecsiparams
	@printf "\033[0;31m  INSTALLING\033[0m %s\n" "makecsiparams"
	$(Q)sudo make -C utils/makecsiparams install

# Collect CSI without dropping the Wi-Fi connection. Requires wlan0 to be
# associated already; pass extra makecsiparams options via CSIARGS, e.g.
#   make -f Makefile.rpi csi-connected CSIARGS="-b 0x88 -m 00:11:22:33:44:55"
csi-connected: is-rpi
	$(Q)sudo utils/csi-connected.sh -i $(IFACE) $(CSIARGS)

csi-stop: is-rpi
	$(Q)sudo utils/csi-connected.sh -i $(IFACE) --stop

csi-status: is-rpi
	$(Q)sudo utils/csi-connected.sh -i $(IFACE) --status

# The 43455 firmware is shipped as a Debian alternative, so the path the driver
# ends up reading is reached through two symlinks:
#
#   brcm/brcmfmac43455-sdio.<board>.bin -> brcm/brcmfmac43455-sdio.bin
#                                       -> cypress/cyfmac43455-sdio.bin   (the alternative)
#                                       -> cypress/cyfmac43455-sdio-standard.bin
#
# Both the board specific name a Pi 5 asks for and the generic fallback resolve
# to the alternative, which is why pointing the alternative at our image is
# enough and why copying over brcm/brcmfmac43455-sdio.bin directly is not just
# unnecessary but harmful: cp follows the links and truncates the distro's own
# firmware, after which --auto has nothing left to restore.
FW_ALTNAME=cyfmac43455-sdio.bin
FW_NEXMON_DIR=/lib/firmware/nexmon

# Where the alternative keeps its link moved between releases - bookworm has it
# under /lib/firmware, trixie under /usr/lib/firmware - and registering a second
# path for a name that already exists silently does nothing at all. So ask
# update-alternatives where the link is instead of hardcoding either answer.
install-firmware: $(RAM_FILE) is-rpi
	@printf "\033[0;31m  COPYING\033[0m %s => %s/%s\n" $(RAM_FILE) $(FW_NEXMON_DIR) $(RAM_FILE)
	$(Q)sudo mkdir -p $(FW_NEXMON_DIR)
	$(Q)sudo cp $(RAM_FILE) $(FW_NEXMON_DIR)/$(RAM_FILE)
	$(Q)set -e; \
	link=$$(update-alternatives --query $(FW_ALTNAME) 2>/dev/null | sed -n 's/^Link: //p' | head -n 1); \
	if [ -z "$$link" ]; then \
	    if [ -d /usr/lib/firmware/cypress ]; then link=/usr/lib/firmware/cypress/$(FW_ALTNAME); \
	    else link=/lib/firmware/cypress/$(FW_ALTNAME); fi; \
	fi; \
	printf "\033[0;31m  SETTING FIRMWARE ALTERNATIVE\033[0m %s => %s/%s\n" "$$link" "$(FW_NEXMON_DIR)" "$(RAM_FILE)"; \
	if [ -e "$$link" ] && [ ! -L "$$link" ]; then \
	    printf "\033[0;31m  BACKING UP\033[0m %s => %s.orig\n" "$$link" "$$link"; \
	    sudo cp -n "$$link" "$$link.orig"; \
	    sudo rm -f "$$link"; \
	fi; \
	sudo update-alternatives --install "$$link" $(FW_ALTNAME) $(FW_NEXMON_DIR)/$(RAM_FILE) 30; \
	sudo update-alternatives --set $(FW_ALTNAME) $(FW_NEXMON_DIR)/$(RAM_FILE)
ifeq ($(RELOAD_DRIVER),0)
	@printf "\033[0;31m  SKIPPING RELOAD\033[0m (RELOAD_DRIVER=0)\n"
	@printf "  the chip still runs its old firmware until the driver reattaches:\n"
	@printf "  sudo utils/reload-brcmfmac.sh -i %s\n" "$(IFACE)"
else
	@printf "\033[0;31m  RELOADING DRIVER\033[0m so the chip reads the new image\n"
	@printf "  this drops the Wi-Fi link - pass RELOAD_DRIVER=0 if you are connected over %s\n" "$(IFACE)"
	$(Q)sudo utils/reload-brcmfmac.sh -i $(IFACE)
	@printf "\033[0;31m  VERIFYING\033[0m the running firmware\n"
	$(Q)banner=$$(sudo dmesg | grep -i 'brcmfmac.*Firmware:' | tail -n 1); \
	case "$$banner" in \
	    *nexmon*) printf "  running: %s\n" "$${banner#*Firmware: }" ;; \
	    "") echo "error: the driver logged no firmware banner, so the chip did not attach - check 'dmesg | tail'" >&2; exit 1 ;; \
	    *) echo "error: the chip came up on firmware that is not the nexmon CSI build:" >&2; \
	       echo "  $${banner#*Firmware: }" >&2; \
	       echo "The alternative was set, so something else answered the driver's request first." >&2; \
	       echo "Check 'update-alternatives --display $(FW_ALTNAME)', and whether a board specific" >&2; \
	       echo "firmware file exists as a real file instead of a symlink to the alternative -" >&2; \
	       echo "the driver asks for brcm/brcmfmac43455-sdio.<board>.bin before the generic name," >&2; \
	       echo "for example brcm/brcmfmac43455-sdio.raspberrypi,5-model-b.bin on a Pi 5." >&2; \
	       exit 1 ;; \
	esac
endif

# --auto on its own is not enough to undo the install. It picks the highest
# priority *registered* alternative, and if the distro never registered one -
# which is the case when install-firmware had to convert a real file into an
# alternative - then ours is the only candidate and --auto happily reselects it,
# reporting success while leaving the CSI firmware in place.
restore-wifi: is-rpi
	@printf "\033[0;31m  SETTING FIRMWARE ALTERNATIVE\033[0m to default $(FW_ALTNAME)\n"
	$(Q)set -e; \
	link=$$(update-alternatives --query $(FW_ALTNAME) 2>/dev/null | sed -n 's/^Link: //p' | head -n 1); \
	others=$$(update-alternatives --query $(FW_ALTNAME) 2>/dev/null | sed -n 's/^Alternative: //p' | grep -v "^$(FW_NEXMON_DIR)/" || true); \
	if [ -n "$$others" ]; then \
	    sudo update-alternatives --auto $(FW_ALTNAME); \
	else \
	    printf "  no packaged alternative is registered, restoring the saved original\n"; \
	    sudo update-alternatives --remove $(FW_ALTNAME) $(FW_NEXMON_DIR)/$(RAM_FILE) || true; \
	    if [ -e "$$link.orig" ]; then \
	        sudo cp "$$link.orig" "$$link"; \
	    else \
	        echo "error: no $$link.orig to restore - reinstall the distro firmware with" >&2; \
	        echo "  sudo apt install --reinstall firmware-brcm80211" >&2; \
	        exit 1; \
	    fi; \
	fi
	@printf "\033[0;31m  RELOADING DRIVER\033[0m %s\n" "brcmfmac"
	$(Q)sudo utils/reload-brcmfmac.sh -i $(IFACE)
	@printf "\033[0;31m  BRINGUP INTERFACE\033[0m %s\n" "$(IFACE)"
	$(Q)sudo ip link set $(IFACE) up
	@printf "\033[0;31m  UNBLOCK RADIO\033[0m\n"
	$(Q)sudo rfkill unblock wifi
	@printf "\033[0;31m  NetworkManager MANAGE\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli dev set $(IFACE) managed yes
	@printf "\033[0;31m  NetworkManager RADIO ON\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli radio wifi on
	$(Q)sleep 1
	@printf "\033[0;31m  NetworkManager CONNECT\033[0m %s\n" "$(IFACE)"
	$(Q)sudo nmcli dev connect $(IFACE)

clean-firmware: FORCE
	$(Q)rm -fr $(RAM_FILE) obj gen log src/ucode_compressed.c src/templateram.c

clean: clean-firmware
	@printf "\033[0;31m  CLEANING\033[0m\n"
	$(Q)rm -f BUILD_NUMBER

FORCE:
